name: kseb-prod
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - flask
  - transformers
  - boto3
  - accelerate
  - python-dotenv
  - opencv
  - pip
  - pip:
    - sentencepiece
