name: KSEB
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # 기본 파이썬 버전
  - python=3.10

  # Conda로 설치할 핵심 라이브러리
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - beautifulsoup4
  - requests
  - pillow
  - pyside6 # Qt for Python
  - opencv
  - openvino
  - pytz
  - pyyaml
  
  # GPU 사용을 위한 PyTorch (CUDA 12.1 기준)
  - pytorch 
  - torchvision 
  - pytorch-cuda=12.1

  # Pip으로 설치할 라이브러리
  - pip
  - pip:
    - ultralytics
    - transformers
    - accelerate
    - datasets
    - evaluate
    - huggingface-hub
    - mediapipe
    - tensorflow-intel
    - openai
    - django
    - python-dotenv