name: KSEB
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - blas=1.0=mkl
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.10.18
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.2.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=4.3.1
  - fontconfig=2.14.1
  - fqdn=1.5.1
  - freeglut=3.4.0
  - freetype=2.10.4
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.14.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.20.1
  - lark=1.2.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libxslt=1.1.41
  - lxml=5.3.0
  - lz4-c=1.9.4
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - minizip=4.0.3
  - mistune=3.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpi4py=3.1.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.1.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.40.0
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2024.1
  - pyzmq=25.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.7.1
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - send2trash=1.8.3
  - setuptools=72.1.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.3
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asgiref==3.9.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - blinker==1.9.0
      - boto3==1.40.7
      - botocore==1.40.7
      - cachetools==5.5.2
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorlog==6.9.0
      - contourpy==1.3.2
      - datasets==4.0.0
      - dill==0.3.8
      - distro==1.9.0
      - django==5.2.4
      - evaluate==0.4.5
      - filelock==3.18.0
      - flask==3.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gast==0.6.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - huggingface-hub==0.34.4
      - itsdangerous==2.2.0
      - jax==0.5.3
      - jaxlib==0.5.3
      - jiter==0.10.0
      - jmespath==1.0.1
      - keras==3.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - namex==0.1.0
      - networkx==3.4.2
      - numpy==1.26.4
      - oauthlib==3.3.1
      - openai==1.93.1
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.16.0
      - optuna==4.4.0
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==4.25.8
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==1.1.1
      - pyttsx3==2.90
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - s3fs==0.4.2
      - s3transfer==0.13.1
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - sounddevice==0.5.2
      - sqlalchemy==2.0.42
      - sqlparse==0.5.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.19.0
      - tensorflow-estimator==2.10.0
      - tensorflow-intel==2.18.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - tf-keras==2.19.0
      - tokenizers==0.21.2
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.55.0
      - typing-inspection==0.4.1
      - ultralytics==8.3.176
      - ultralytics-thop==2.0.14
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.1
