name: kseb-prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask
  - transformers
  - boto3
  - accelerate
  - python-dotenv
  - opencv
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - --index-url https://download.pytorch.org/whl/cu121
    - sentencepiece
